### ISSUE TITLE
Does Knowledge Enhancer always guarantee satisfaction of constraints? 

### ISSUE THREAD

**Issue by ereday** [DanieleAlessandro/KENN#6]
Hi, 

First of all, thank you for sharing the code. I have a simple question about KENN and I'll use the example given in the README while asking it. 

Let's assume the knowledge base  consists of two simple clauses:
```
1:nDog,Animal
1:nCat,Animal

```

These two rules tell that whenever dog (or cat) is predicted, animal should also be predicted. Is the [implementation](https://github.com/DanieleAlessandro/KENN/blob/master/kenn/Clause.py#L89-L103) of knowledge enhancer in this repository actually be able to guarantee this? 

Thanks!

**Comment by DanieleAlessandro** [comment]
Hi,
no, it is not guaranteed. In general, the higher is the weight, the higher is the truth value of the clause.

Please note that the clause weights values do not need to be in the range [0,1], the only requirement is for them to be positive. Usually, if you use a higher value (for instance 10) the rules will be satisfied. However, there are no guarantees.

More in details, the weights should be interpreted as the change applied to the literals values' pre-activations. For more details, please give a look at our paper:

https://arxiv.org/pdf/2009.06087.pdf
